In [1]:
import numpy as np
from utils.data import extract_eeg_data, segment_data, kfold_split
from utils.labels import get_pss_labels, get_stai_labels
from utils.valid_recs import get_valid_recs
from features import time_series_features, fractal_features, entropy_features, hjorth_features, freq_band_features
from classifiers import knn_classification, svm_classification, nn_classification
import utils.variables as v

In [2]:
valid_recs = get_valid_recs(data_type='ica')
x_dict = extract_eeg_data(valid_recs, data_type='ica')

Creating RawArray with float64 data, n_channels=8, n_times=75072
    Range : 0 ... 75071 =      0.000 ...   300.284 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75168
    Range : 0 ... 75167 =      0.000 ...   300.668 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75024
    Range : 0 ... 75023 =      0.000 ...   300.092 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75040
    Range : 0 ... 75039 =      0.000 ...   300.156 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75536
    Range : 0 ... 75535 =      0.000 ...   302.140 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75760
    Range : 0 ... 75759 =      0.000 ..

ERROR:root:1) Failed to read data for recording P006_S002_001
ERROR:root:1) Failed to read data for recording P006_S002_002


Creating RawArray with float64 data, n_channels=8, n_times=75152
    Range : 0 ... 75151 =      0.000 ...   300.604 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75040
    Range : 0 ... 75039 =      0.000 ...   300.156 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=82688
    Range : 0 ... 82687 =      0.000 ...   330.748 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75664
    Range : 0 ... 75663 =      0.000 ...   302.652 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75200
    Range : 0 ... 75199 =      0.000 ...   300.796 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75424
    Range : 0 ... 75423 =      0.000 ...   301.692 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75328
    Range : 0 ... 75327 =      0.000 ...   301.308 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75552
    Range : 0 ... 75551 =      0.000 ..

ERROR:root:1) Failed to read data for recording P013_S002_001
ERROR:root:1) Failed to read data for recording P013_S002_002


Creating RawArray with float64 data, n_channels=8, n_times=75072
    Range : 0 ... 75071 =      0.000 ...   300.284 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75296
    Range : 0 ... 75295 =      0.000 ...   301.180 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75184
    Range : 0 ... 75183 =      0.000 ...   300.732 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75312
    Range : 0 ... 75311 =      0.000 ...   301.244 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75056
    Range : 0 ... 75055 =      0.000 ...   300.220 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75040
    Range : 0 ... 75039 =      0.000 ...   300.156 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75184
    Range : 0 ... 75183 =      0.000 ...   300.732 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75296
    Range : 0 ... 75295 =      0.000 ..

ERROR:root:1) Failed to read data for recording P028_S001_001
ERROR:root:1) Failed to read data for recording P028_S001_002
ERROR:root:1) Failed to read data for recording P028_S002_001
ERROR:root:1) Failed to read data for recording P028_S002_002


Creating RawArray with float64 data, n_channels=8, n_times=75072
    Range : 0 ... 75071 =      0.000 ...   300.284 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75168
    Range : 0 ... 75167 =      0.000 ...   300.668 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75024
    Range : 0 ... 75023 =      0.000 ...   300.092 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75040
    Range : 0 ... 75039 =      0.000 ...   300.156 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75536
    Range : 0 ... 75535 =      0.000 ...   302.140 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75760
    Range : 0 ... 75759 =      0.000 ..

In [3]:
y_dict = get_stai_labels(valid_recs, low_cutoff=37, high_cutoff=38) 
#y_dict = get_pss_labels(valid_recs)

In [4]:
x_epochs, y_epochs = segment_data(x_dict, y_dict, epoch_duration=3)
splits = kfold_split(x_epochs, y_epochs, n_splits=5, shuffle=True, random_state=42)
train_epochs, test_epochs, train_labels, test_labels = splits

y_train = [np.array([v for _, v in train_labels[i].items()]) for i in range(len(train_labels))]
y_test = [np.array([v for _, v in test_labels[i].items()]) for i in range(len(test_labels))]

x_train = hjorth_features(train_epochs)
x_test = hjorth_features(test_epochs)
# freq_bands = np.array([1, 4, 8, 12, 30, 50])
# features = freq_band_features(dataset, freq_bands)
# features = hjorth_features(dataset)
# features = entropy_features(dataset)
#  features = fractal_features(dataset)

Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time po

c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\model_selection\_split.py:684: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(


### KNN

In [5]:
print('ica data')
knn_classification(x_train, x_test, y_train, y_test)

ica data

Results for fold 1:
              precision    recall  f1-score   support

           0       0.53      0.50      0.52      1198
           1       0.00      0.00      0.00         0
           2       0.19      0.16      0.17       900

    accuracy                           0.35      2098
   macro avg       0.24      0.22      0.23      2098
weighted avg       0.39      0.35      0.37      2098

[[597   1 600]
 [  0   0   0]
 [520 240 140]]


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Results for fold 2:
              precision    recall  f1-score   support

           0       0.57      0.76      0.65      1099
           1       0.00      0.00      0.00         0
           2       0.51      0.27      0.35      1000

    accuracy                           0.53      2099
   macro avg       0.36      0.34      0.34      2099
weighted avg       0.54      0.53      0.51      2099

[[840   1 258]
 [  0   0   0]
 [635  96 269]]


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Results for fold 3:
              precision    recall  f1-score   support

           0       0.59      0.66      0.62      1099
           1       0.00      0.00      0.00       100
           2       0.53      0.50      0.52       900

    accuracy                           0.56      2099
   macro avg       0.37      0.39      0.38      2099
weighted avg       0.54      0.56      0.55      2099

[[730   0 369]
 [ 76   0  24]
 [440   9 451]]

Results for fold 4:
              precision    recall  f1-score   support

           0       0.56      0.58      0.57      1099
           1       0.00      0.00      0.00       100
           2       0.41      0.45      0.43       900

    accuracy                           0.49      2099
   macro avg       0.32      0.34      0.33      2099
weighted avg       0.47      0.49      0.48      2099

[[632   0 467]
 [  0   0 100]
 [499   0 401]]


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Results for fold 5:
              precision    recall  f1-score   support

           0       0.42      0.42      0.42      1100
           2       0.29      0.28      0.29       900

    accuracy                           0.36      2000
   macro avg       0.35      0.35      0.35      2000
weighted avg       0.36      0.36      0.36      2000

[[466 634]
 [645 255]]


### SVM

In [6]:
print('ica data')
print(svm_classification(x_train, x_test, y_train, y_test))


ica data

Results for fold 1:
              precision    recall  f1-score   support

           0       0.60      0.50      0.55      1198
           1       0.00      0.00      0.00         0
           2       0.40      0.44      0.42       900

    accuracy                           0.48      2098
   macro avg       0.33      0.32      0.32      2098
weighted avg       0.51      0.48      0.49      2098

[[603   0 595]
 [  0   0   0]
 [409  93 398]]


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Results for fold 2:
              precision    recall  f1-score   support

           0       0.61      0.89      0.73      1099
           1       0.00      0.00      0.00         0
           2       0.75      0.34      0.47      1000

    accuracy                           0.63      2099
   macro avg       0.45      0.41      0.40      2099
weighted avg       0.68      0.63      0.60      2099

[[983   0 116]
 [  0   0   0]
 [620  37 343]]


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Results for fold 3:
              precision    recall  f1-score   support

           0       0.60      0.59      0.59      1099
           1       0.00      0.00      0.00       100
           2       0.46      0.52      0.49       900

    accuracy                           0.53      2099
   macro avg       0.35      0.37      0.36      2099
weighted avg       0.51      0.53      0.52      2099

[[645   0 454]
 [  0   0 100]
 [429   0 471]]


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Results for fold 4:
              precision    recall  f1-score   support

           0       0.56      0.60      0.58      1099
           1       0.00      0.00      0.00       100
           2       0.42      0.43      0.43       900

    accuracy                           0.50      2099
   macro avg       0.33      0.34      0.34      2099
weighted avg       0.47      0.50      0.49      2099

[[659   0 440]
 [  0   0 100]
 [510   0 390]]


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Results for fold 5:
              precision    recall  f1-score   support

           0       0.54      0.54      0.54      1100
           1       0.00      0.00      0.00         0
           2       0.43      0.44      0.44       900

    accuracy                           0.49      2000
   macro avg       0.32      0.32      0.32      2000
weighted avg       0.49      0.49      0.49      2000

[[589   1 510]
 [  0   0   0]
 [507   1 392]]
None


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Neural Network

In [7]:
print('ica data')
nn_classification(x_train, x_test, y_train, y_test)


ica data


TypeError: nn_classification() takes 2 positional arguments but 4 were given