In [28]:
import numpy as np
from sklearn.model_selection import train_test_split, train_test_split
import pandas as pd

from utils.data import extract_eeg_data, segment_data, kfold_split
from utils.labels import get_pss_labels, get_stai_labels
from utils.valid_recs import get_valid_recs
from features import all_features, hjorth_features
from classifiers import knn_classification, svm_classification, cnn_classification
import utils.variables as v

In [2]:
valid_recs = get_valid_recs(data_type='ica', output_type = 'np')

x_dict = extract_eeg_data(valid_recs, data_type='ica', output_type='np')


Creating RawArray with float64 data, n_channels=8, n_times=75072
    Range : 0 ... 75071 =      0.000 ...   300.284 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75168
    Range : 0 ... 75167 =      0.000 ...   300.668 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75024
    Range : 0 ... 75023 =      0.000 ...   300.092 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75040
    Range : 0 ... 75039 =      0.000 ...   300.156 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75536
    Range : 0 ... 75535 =      0.000 ...   302.140 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75760
    Range : 0 ... 75759 =      0.000 ..

ERROR:root:1) Failed to read data for recording P006_S002_001
ERROR:root:1) Failed to read data for recording P006_S002_002


Creating RawArray with float64 data, n_channels=8, n_times=75152
    Range : 0 ... 75151 =      0.000 ...   300.604 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75040
    Range : 0 ... 75039 =      0.000 ...   300.156 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=82688
    Range : 0 ... 82687 =      0.000 ...   330.748 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75664
    Range : 0 ... 75663 =      0.000 ...   302.652 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75200
    Range : 0 ... 75199 =      0.000 ...   300.796 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75424
    Range : 0 ... 75423 =      0.000 ...   301.692 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75328
    Range : 0 ... 75327 =      0.000 ...   301.308 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75552
    Range : 0 ... 75551 =      0.000 ..

ERROR:root:1) Failed to read data for recording P028_S001_001
ERROR:root:1) Failed to read data for recording P028_S001_002


Creating RawArray with float64 data, n_channels=8, n_times=75424
    Range : 0 ... 75423 =      0.000 ...   301.692 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75312
    Range : 0 ... 75311 =      0.000 ...   301.244 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75072
    Range : 0 ... 75071 =      0.000 ...   300.284 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75168
    Range : 0 ... 75167 =      0.000 ...   300.668 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75584
    Range : 0 ... 75583 =      0.000 ...   302.332 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75024
    Range : 0 ... 75023 =      0.000 ...   300.092 secs
Ready.
Creating RawArray with float64 data, n_channels=8, n_times=75040
    Range : 0 ... 75039 =      0.000 ..

In [3]:
y_dict = get_stai_labels(valid_recs) 
#y_dict = get_pss_labels(valid_recs)

    SubjectNo  D1Y1  D2Y1  J1Y1  J2Y1
0           1    26    30    29    31
1           2    38    41    26    34
2           3    58    56    36    35
3           4    40    45    24    24
4           5    25    31    38    37
5           6    49    58     0     0
6           7    56    50    28    28
7           8    46    37    23    27
8           9    41    47    27    22
9          10    37    20    23    21
10         11    50    49    31    47
11         12    42    47    47    41
12         13    35    35    28    33
13         14    54    35    26    26
14         15    51    55    33    42
15         16    35    38    42    45
16         17    37    35    24    20
17         18    54    62    41    48
18         19    47    52    30    36
19         20    46    38    24    25
20         21    44    54    33    39
21         22    49    51    28    34
22         23    56    53    33    28
23         24    52    58    36    41
24         25    48    62    29    56
25         2

In [4]:
print(len(x_dict))
print(len(y_dict))

108
108


In [5]:
targ_val = 1
rem=[]
for i in y_dict.keys():
    if y_dict[i] is targ_val:
        rem.append(i)
# printing result
print("\nThe extracted keys : \n" + str(rem))

[y_dict.pop(key) for key in rem]
[x_dict.pop(key) for key in rem]
print(f"\nDictionary after removal of keys from y_dict: \n {y_dict.keys()}")
print(f"\nDictionary after removal of keys from x_dict: \n {x_dict.keys()}")


The extracted keys : 
['P002_S001_001', 'P002_S001_002', 'P004_S001_001', 'P004_S001_002', 'P005_S002_001', 'P005_S002_002', 'P008_S001_002', 'P009_S001_001', 'P010_S001_001', 'P012_S001_001', 'P012_S002_002', 'P015_S002_002', 'P016_S001_002', 'P016_S002_001', 'P016_S002_002', 'P017_S001_001', 'P018_S002_001', 'P020_S001_002', 'P021_S001_001', 'P021_S002_002', 'P024_S002_002', 'P026_S001_001', 'P026_S001_002', 'P027_S001_002', 'P027_S002_001']

Dictionary after removal of keys from y_dict: 
 dict_keys(['P001_S001_001', 'P001_S001_002', 'P001_S002_001', 'P001_S002_002', 'P002_S002_001', 'P002_S002_002', 'P003_S001_001', 'P003_S001_002', 'P003_S002_001', 'P003_S002_002', 'P004_S002_001', 'P004_S002_002', 'P005_S001_001', 'P005_S001_002', 'P006_S001_001', 'P006_S001_002', 'P007_S001_001', 'P007_S001_002', 'P007_S002_001', 'P007_S002_002', 'P008_S001_001', 'P008_S002_001', 'P008_S002_002', 'P009_S001_002', 'P009_S002_001', 'P009_S002_002', 'P010_S001_002', 'P010_S002_001', 'P010_S002_002'

In [6]:
x_epochs, y_epochs = segment_data(x_dict, y_dict, epoch_duration=3)


Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time points ...
0 bad epochs dropped
Not setting metadata
100 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 100 events and 751 original time po

In [13]:
#print(x_epochs)

#x_epochs_df = pd.DataFrame.from_dict(x_epochs)


In [10]:
splits = kfold_split(x_epochs, y_epochs, n_splits=2, shuffle=True, random_state=42)
train_epochs, test_epochs, train_labels, test_labels = splits
y_train = [np.array([v for _, v in train_labels[i].items()]) for i in range(len(train_labels))]
y_test = [np.array([v for _, v in test_labels[i].items()]) for i in range(len(test_labels))]


#x, x_test, y, test_labels = train_test_split(x_epochs, y_epochs, test_size=0.2, random_state=1)
#x_train, x_val, train_labels, val_labels = train_test_split(x, y, test_size=0.25, random_state=1)


# freq_bands = np.array([1, 4, 8, 12, 30, 50])
# features = freq_band_features(dataset, freq_bands)
# features = hjorth_features(dataset)
# features = entropy_features(dataset)
#  features = fractal_features(dataset)

In [14]:
x_train = hjorth_features(train_epochs) 
x_test = hjorth_features(test_epochs)

### KNN

In [15]:
print('ica data')
knn_classification(x_train, x_test, y_train, y_test)

ica data

Results for fold 1:
              precision    recall  f1-score   support

           0       0.57      0.56      0.56      2498
           2       0.36      0.36      0.36      1699

    accuracy                           0.48      4197
   macro avg       0.46      0.46      0.46      4197
weighted avg       0.48      0.48      0.48      4197

[[1405 1093]
 [1079  620]]

Results for fold 2:
              precision    recall  f1-score   support

           0       0.56      0.53      0.55      2499
           2       0.33      0.36      0.35      1600

    accuracy                           0.46      4099
   macro avg       0.45      0.45      0.45      4099
weighted avg       0.47      0.46      0.47      4099

[[1322 1177]
 [1019  581]]


### SVM

In [16]:
print('ica data')
print(svm_classification(x_train, x_test, y_train, y_test))


ica data

Results for fold 1:
              precision    recall  f1-score   support

           0       0.53      0.35      0.42      2498
           2       0.36      0.54      0.43      1699

    accuracy                           0.43      4197
   macro avg       0.44      0.44      0.43      4197
weighted avg       0.46      0.43      0.42      4197

[[ 864 1634]
 [ 778  921]]

Results for fold 2:
              precision    recall  f1-score   support

           0       0.62      0.65      0.63      2499
           2       0.40      0.37      0.39      1600

    accuracy                           0.54      4099
   macro avg       0.51      0.51      0.51      4099
weighted avg       0.53      0.54      0.54      4099

[[1617  882]
 [1002  598]]
None


# Convolutional Neural Network

In [34]:

print(len(x_train[0]))
print(len(y_train[0]))

print(len(x_train[1]))
print(len(y_train[1]))

print(len(x_test[0]))
print(len(y_test[0]))

print(len(x_test[1]))
print(len(y_test[1]))

4099
4099
4197
4197
4197
4197
4099
4099


In [29]:
print('ica data')
cnn_classification(x_train, x_test, y_train, y_test)


ica data


ValueError: Data cardinality is ambiguous:
  x sizes: 4099, 4197
  y sizes: 4197, 4099
Make sure all arrays contain the same number of samples.