In [1]:
import numpy as np
from sklearn.model_selection import train_test_split, train_test_split
import pandas as pd

from utils.data import extract_eeg_data, segment_data
from load_data import load_kfold_data
from utils.labels import get_pss_labels, get_stai_labels
from utils.valid_recs import get_valid_recs
from features import all_features, hjorth_features, differential_entropy, kymatio_wave_scattering
from classifiers import knn_classification, svm_classification

import utils.variables as v

In [2]:
data_type = 'raw'
label_type = 'pss'

#train_data, test_data, val_data, train_labels, test_labels, val_labels = load_data(data_type, label_type, epoched = True, binary = True)
train_data, test_data, train_labels, test_labels = load_kfold_data(data_type, label_type, epoched = False, binary = True)

print(train_data.shape)
print(train_labels.shape)
#Reshape data
train_data = np.reshape(train_data, (train_data.shape[0]*train_data.shape[1], train_data.shape[2]))
train_labels = np.repeat(train_labels, repeats = 8, axis = 1).reshape(-1,1)
print(train_data.shape)
print(train_labels.shape)

test_data = np.reshape(test_data, (test_data.shape[0]*test_data.shape[1],test_data.shape[2]))
test_labels = np.repeat(test_labels, repeats = 8, axis = 1).reshape(-1,1)
print(test_data.shape)
print(test_labels.shape)

---- Generating all recordings ----
All records generated

---- Filtering out invalid recordings ----
ERROR 1) Failed to read data for recording P006_S002_001
ERROR 1) Failed to read data for recording P006_S002_002
ERROR 1) Failed to read data for recording P028_S002_001
ERROR 1) Failed to read data for recording P028_S002_002

---- Returning valid recordings ----
['P001_S001_001', 'P001_S001_002', 'P001_S002_001', 'P001_S002_002', 'P002_S001_001', 'P002_S001_002', 'P002_S002_001', 'P002_S002_002', 'P003_S001_001', 'P003_S001_002', 'P003_S002_001', 'P003_S002_002', 'P004_S001_001', 'P004_S001_002', 'P004_S002_001', 'P004_S002_002', 'P005_S001_001', 'P005_S001_002', 'P005_S002_001', 'P005_S002_002', 'P006_S001_001', 'P006_S001_002', 'P007_S001_001', 'P007_S001_002', 'P007_S002_001', 'P007_S002_002', 'P008_S001_001', 'P008_S001_002', 'P008_S002_001', 'P008_S002_002', 'P009_S001_001', 'P009_S001_002', 'P009_S002_001', 'P009_S002_002', 'P010_S001_002', 'P010_S002_001', 'P010_S002_002', 'P

In [3]:
#x, x_test, y, test_labels = train_test_split(x_epochs, y_epochs, test_size=0.2, random_state=1)
#x_train, x_val, train_labels, val_labels = train_test_split(x, y, test_size=0.25, random_state=1)


# freq_bands = np.array([1, 4, 8, 12, 30, 50])
# features = freq_band_features(dataset, freq_bands)
# features = hjorth_features(dataset)
# features = entropy_features(dataset)
# features = fractal_features(dataset)

In [4]:
print(f'{data_type} data with {label_type} labels')
knn_classification(train_data, test_data, train_labels, test_labels)

raw data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)



Results:
Classification accuracy: 0.638889 

 Confusion matrix:
[[64  0]
 [24  8]]
Accuracy, Sensitivity, Specificity:

[ 75.    72.73 100.  ]


In [5]:
print(f'{data_type} data with {label_type} labels')
svm_classification(train_data, test_data, train_labels, test_labels)


raw data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please 


Results:
Classification accuracy: 0.541667 

 Confusion matrix:
[[56  8]
 [ 4 28]]
Accuracy, Sensitivity, Specificity:

[87.5  93.33 77.78]


In [6]:
data_type = 'init'
label_type = 'pss'

#train_data, test_data, val_data, train_labels, test_labels, val_labels = load_data(data_type, label_type, epoched = True, binary = True)
train_data, test_data, train_labels, test_labels = load_kfold_data(data_type, label_type, epoched = False, binary = True)

print(train_data.shape)
print(train_labels.shape)
#Reshape data
train_data = np.reshape(train_data, (train_data.shape[0]*train_data.shape[1], train_data.shape[2]))
train_labels = np.repeat(train_labels, repeats = 8, axis = 1).reshape(-1,1)
print(train_data.shape)
print(train_labels.shape)

test_data = np.reshape(test_data, (test_data.shape[0]*test_data.shape[1],test_data.shape[2]))
test_labels = np.repeat(test_labels, repeats = 8, axis = 1).reshape(-1,1)
print(test_data.shape)
print(test_labels.shape)

---- Generating all recordings ----
All records generated

---- Filtering out invalid recordings ----
ERROR 1) Failed to read data for recording P006_S002_001
ERROR 1) Failed to read data for recording P006_S002_002
ERROR 1) Failed to read data for recording P010_S001_001
ERROR 1) Failed to read data for recording P013_S001_001
ERROR 1) Failed to read data for recording P013_S001_002
ERROR 1) Failed to read data for recording P020_S001_001
ERROR 1) Failed to read data for recording P023_S002_002
ERROR 1) Failed to read data for recording P028_S001_001
ERROR 1) Failed to read data for recording P028_S001_002

---- Returning valid recordings ----
['P001_S001_001', 'P001_S001_002', 'P001_S002_001', 'P001_S002_002', 'P002_S001_001', 'P002_S001_002', 'P002_S002_001', 'P002_S002_002', 'P003_S001_001', 'P003_S001_002', 'P003_S002_001', 'P003_S002_002', 'P004_S001_001', 'P004_S001_002', 'P004_S002_001', 'P004_S002_002', 'P005_S001_001', 'P005_S001_002', 'P005_S002_001', 'P005_S002_002', 'P006_

In [7]:
print(f'{data_type} data with {label_type} labels')
knn_classification(train_data, test_data, train_labels, test_labels)

init data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)



Results:
Classification accuracy: 0.666667 

 Confusion matrix:
[[64  0]
 [32  0]]
Null error in specificity
Accuracy, Sensitivity, Specificity:

[66.67 66.67  0.  ]


In [8]:
print(f'{data_type} data with {label_type} labels')
svm_classification(train_data, test_data, train_labels, test_labels)

init data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please 


Results:
Classification accuracy: 0.666667 

 Confusion matrix:
[[64  0]
 [32  0]]
Null error in specificity
Accuracy, Sensitivity, Specificity:

[66.67 66.67  0.  ]


In [9]:
data_type = 'ica'
label_type = 'pss'

#train_data, test_data, val_data, train_labels, test_labels, val_labels = load_data(data_type, label_type, epoched = True, binary = True)
train_data, test_data, train_labels, test_labels = load_kfold_data(data_type, label_type, epoched = False, binary = True)

print(train_data.shape)
print(train_labels.shape)
#Reshape data
train_data = np.reshape(train_data, (train_data.shape[0]*train_data.shape[1], train_data.shape[2]))
train_labels = np.repeat(train_labels, repeats = 8, axis = 1).reshape(-1,1)
print(train_data.shape)
print(train_labels.shape)

test_data = np.reshape(test_data, (test_data.shape[0]*test_data.shape[1],test_data.shape[2]))
test_labels = np.repeat(test_labels, repeats = 8, axis = 1).reshape(-1,1)
print(test_data.shape)
print(test_labels.shape)

---- Generating all recordings ----
All records generated

---- Filtering out invalid recordings ----
ERROR 1) Failed to read data for recording P006_S002_001
ERROR 1) Failed to read data for recording P006_S002_002
ERROR 1) Failed to read data for recording P028_S001_001
ERROR 1) Failed to read data for recording P028_S001_002

---- Returning valid recordings ----
['P001_S001_001', 'P001_S001_002', 'P001_S002_001', 'P001_S002_002', 'P002_S001_001', 'P002_S001_002', 'P002_S002_001', 'P002_S002_002', 'P003_S001_001', 'P003_S001_002', 'P003_S002_001', 'P003_S002_002', 'P004_S001_001', 'P004_S001_002', 'P004_S002_001', 'P004_S002_002', 'P005_S001_001', 'P005_S001_002', 'P005_S002_001', 'P005_S002_002', 'P006_S001_001', 'P006_S001_002', 'P007_S001_001', 'P007_S001_002', 'P007_S002_001', 'P007_S002_002', 'P008_S001_001', 'P008_S001_002', 'P008_S002_001', 'P008_S002_002', 'P009_S001_001', 'P009_S001_002', 'P009_S002_001', 'P009_S002_002', 'P010_S001_002', 'P010_S002_001', 'P010_S002_002', 'P

In [10]:
print(f'{data_type} data with {label_type} labels')
knn_classification(train_data, test_data, train_labels, test_labels)

ica data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)



Results:
Classification accuracy: 0.645833 

 Confusion matrix:
[[59  5]
 [31  1]]
Accuracy, Sensitivity, Specificity:

[62.5  65.56 16.67]


In [11]:
print(f'{data_type} data with {label_type} labels')
svm_classification(train_data, test_data, train_labels, test_labels)

ica data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please 


Results:
Classification accuracy: 0.663194 

 Confusion matrix:
[[64  0]
 [31  1]]
Accuracy, Sensitivity, Specificity:

[ 67.71  67.37 100.  ]


In [12]:
data_type = 'new_ica'
label_type = 'pss'

#train_data, test_data, val_data, train_labels, test_labels, val_labels = load_data(data_type, label_type, epoched = True, binary = True)
train_data, test_data, train_labels, test_labels = load_kfold_data(data_type, label_type, epoched = False, binary = True)

print(train_data.shape)
print(train_labels.shape)
#Reshape data
train_data = np.reshape(train_data, (train_data.shape[0]*train_data.shape[1], train_data.shape[2]))
train_labels = np.repeat(train_labels, repeats = 8, axis = 1).reshape(-1,1)
print(train_data.shape)
print(train_labels.shape)

test_data = np.reshape(test_data, (test_data.shape[0]*test_data.shape[1],test_data.shape[2]))
test_labels = np.repeat(test_labels, repeats = 8, axis = 1).reshape(-1,1)
print(test_data.shape)
print(test_labels.shape)

---- Generating all recordings ----
All records generated

---- Filtering out invalid recordings ----
ERROR 1) Failed to read data for recording P006_S002_001
ERROR 1) Failed to read data for recording P006_S002_002
ERROR 1) Failed to read data for recording P010_S001_001
ERROR 1) Failed to read data for recording P013_S001_001
ERROR 1) Failed to read data for recording P013_S001_002
ERROR 1) Failed to read data for recording P020_S001_001
ERROR 1) Failed to read data for recording P023_S002_002
ERROR 1) Failed to read data for recording P028_S001_001
ERROR 1) Failed to read data for recording P028_S001_002

---- Returning valid recordings ----
['P001_S001_001', 'P001_S001_002', 'P001_S002_001', 'P001_S002_002', 'P002_S001_001', 'P002_S001_002', 'P002_S002_001', 'P002_S002_002', 'P003_S001_001', 'P003_S001_002', 'P003_S002_001', 'P003_S002_002', 'P004_S001_001', 'P004_S001_002', 'P004_S002_001', 'P004_S002_002', 'P005_S001_001', 'P005_S001_002', 'P005_S002_001', 'P005_S002_002', 'P006_

In [13]:
print(f'{data_type} data with {label_type} labels')
knn_classification(train_data, test_data, train_labels, test_labels)

new_ica data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)



Results:
Classification accuracy: 0.666667 

 Confusion matrix:
[[64  0]
 [32  0]]
Null error in specificity
Accuracy, Sensitivity, Specificity:

[66.67 66.67  0.  ]


In [14]:
print(f'{data_type} data with {label_type} labels')
svm_classification(train_data, test_data, train_labels, test_labels)

new_ica data with pss labels


c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\annej\anaconda3\envs\MNE\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please 


Results:
Classification accuracy: 0.666667 

 Confusion matrix:
[[64  0]
 [32  0]]
Null error in specificity
Accuracy, Sensitivity, Specificity:

[66.67 66.67  0.  ]
